version: "3.8"

services:
  node-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes: 
      - .:/app # Mount the project directory
      - node_modules:/app/node_modules # Use a named volume for node_modules
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8090:8080"

volumes:
  node_modules: # Define the named volume
